### PR TITLE
Fake review()

### PR DESCRIPTION
**Pull request by MalaZerb**
I added my fakeReview into GetHub
@mvsine @Parkertopak do you mind looking at my code?

### CODE REVIEW

**Review by mvsine — COMMENTED** [review]
You code looks really good. I would take out the punctuation or tell the computer that punctuation also shows the end of a word. Good job.

**Comment by MalaZerb** [comment]
Thank you, Just changed it!

**Comment by Parkertopak** [comment]
Your code is looking great, the only thing that I would want to do is add more comments so that other people that have never read this code before understands whats going on.

**Comment by MalaZerb** [comment]
Thank you! Just updated my code now

**Pull request merged**
